### ISSUE TITLE
Melhorias referentes ao trabalho

### ISSUE THREAD

**Issue by brenobhvm** [healfull/tccfeiras#20]
1 - incluir no cadastro de trabalho a extensão odt para envio.

2 - no cadastro de trabalho incluir a serie dos alunos: fundamental 6º, 7º, 8º e 9º anos. Médio 1º, 2º e 3º anos. Tecnico 1º ao 7º semestre.

3 - incluir um passo a passo no envio de trabalho

4 - incluir 3 avaliadores por trabalho.

5 - mostrar as observações dos trabalhos nas informações do trabalho.

6 - acrescentar um status intermediário de trabalho ex: recusado com ressalvas. Para que possa ser refeito e reavaliado.

7 - armazenar todos os trabalhos enviados. Validar para que o ultimo seja sempre o "oficial" os demais ficam apenas para manter o histórico.

8 - Todas as avaliações finais do trabalho devem ser mostradas nas informações do trabalho.

**Comment by healfull** [comment]
1 - Extensão ODT adicionada nas validações JS e PHP.

2 - Criado a tabela série com as categorias e séries especificadas. Adicionado no Add, Edit e Index do trabalho e nos filtros das áreas de avaliação.

3 - Isso será feito em outro issue (#23), que vai introduzir as páginas de ajuda.

4 - Introduzido o principio da lógica para até 3 avaliações por trabalho. O resto será concluído no issue #17. A action/view "atribuir" foi alterada para "avaliacoes".

5 - Agora todas as avaliações feitas são apresentadas na view do trabalho.

6 - Acrescentado o status Correção. Quando nesse status o botão é liberado um botão apra um tela de reenvio para o Orientador.

7 - Opção de verão adicionada, da para fazer o download de qualquer uma das versões, por padrão, se tentar bular o sistema, sempre vai vir a ultima.

7.5 - Por enquanto o sistema só esta preparado para duas versões do trabalho. O Add/Edit adiciona uma versão 1 e o reenvio uma versão 2. Liberado assim para fins de teste, depois será melhorado em outro issue.

8 - Mesmo que o 5.

9 - Adicionado o controle de renderização por ACL no getLink;
