### ISSUE TITLE
Melhorias das telas e cadastros

### ISSUE THREAD

**Issue by brenobhvm** [healfull/tccfeiras#21]
1 - mudar tela de login e cadastro passar para o template do sistema.

2 - separar os cadastros de avaliadores e orientadores

3 - incluir um campo para o lattes e um campo para a area de interesse do avaliador.

4 - no cadastro de instituições incluir o tipo: estadual, municipal, particular, federal e militar.

5 - no cadastro de orientador/avaliador colocar um campo para selecionar a feira de interesse.

6 - link fixo na pagina de submissão para a tela de login/cadastro.

**Comment by healfull** [comment]
Isto foi feito já não foi?
